GET http://localhost:4000/me

###
GET http://localhost:4000/heroes

###
POST http://localhost:4000/heroes
Content-Type: application/json

{
	"id": "69",
	"name": "Batman",
	"powerstats": {
		"intelligence": "81",
		"strength": "40",
		"speed": "29",
		"durability": "55",
		"power": "63",
		"combat": "90"
	},
	"biography": {
		"full-name": "Terry McGinnis",
		"alter-egos": "No alter egos found.",
		"aliases": ["The Tomorrow Knight"],
		"place-of-birth": "Gotham City, 25th Century",
		"first-appearance": "Batman Beyond #1",
		"publisher": "DC Comics",
		"alignment": "good"
	}
}

###
GET http://localhost:4000/heroes/60e46e138b722023ac406e1b

###

GET http://localhost:4000/heroes/bio/60e45294c308fa040c8e23eb

###

PATCH http://localhost:4000/heroes/60e59f9a20f54530d82eab41
Content-Type: application/json

{
	"name":"Superman"
}

###

DELETE http://localhost:4000/heroes/60e45294c308fa040c8e23eb

###


POST http://localhost:4000/users
Content-Type: application/json

{
	"email": "medhi@email.com",
	"password": "medhi",
	"role": "user"
}

###
GET http://localhost:4000/users
  
